config/routes.rb
Rails.application.routes.draw do
  root 'index#index'
  get  'home/about'

  scope module: 'index' do
    get 'buddix', as: :buddix_info
    get 'terms_of_service'
    get 'privacypolicy'
    get 'corp'
    get 'faq'
  end

  #resource :facebook_user, only: [] do
  #  get 'login_oauth'
  #  get 'login_oauth_callback'
  #  get 'edit_oauth'
  #  get 'edit_oauth_callbak'
  #end

  resources :users, :only => [:show]
    get     'login',   to: 'sessions#new'
    post    'login',   to: 'sessions#create'
    delete  'logout',  to: 'sessions#destroy'

    get 'checkmail', to: "users#checkmail"

  get "/users_info" => "users_info#new", as: :users_info
  post "/users_info" => "users_info#create"


  if Rails.env.development? #開発環境の場合
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gift.rb
class Gift < ApplicationRecord

  resourcify :authorities, role_name: 'Authority' 

  has_many :user_gifts
  has_many :users, through: :user_gifts
end

app/models/user.rb
class User < ApplicationRecord

  resourcify :authorities, role_name: 'Authority'

  has_many :user_gifts
  has_many :gifts, through: :user_gifts
end

app/models/user_gift.rb
class UserGift < ApplicationRecord
  belongs_to :user
  belongs_to :gift
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery

  before_action :set_root_title

  def set_root_title
    @root_title = "BuddiX (バディックス)"
  end

  #exception
  rescue_from Exception, with: :error_500_internal_server_error
  rescue_from ActiveRecord::RecordNotFound, with: :error_404_not_found
  rescue_from ActionController::RoutingError, with: :error_404_not_found

  rescue_from CustomNotFound, with: :error_404_not_found
  rescue_from CustomForbidden, with: :error_403_forbidden
  rescue_from CustomClientError, with: :error_400_invalied


  def error_404_not_found(exception=nil)
    logger.debug "# error_404_not_found"

    if exception
      logger.debug "#{exception.class}:#{exception.message}"
      logger.debug exception.backtrace.first
    end

    @error_title = '404 error'

    render template: 'errors/404_not_found', status: 404, layout:'application', content_type: 'text/html'
  end

  def error_500_internal_server_error(exception=nil)
    logger.debug "# error_500_internal_server_error"

    if exception
      logger.debug "#{exception.class}:#{exception.message}"
      logger.debug exception.backtrace.first
    end

    @error_title = '500 error'
    @msg = "サーバーでエラーが起こりました"

    render template: 'errors/500_internal_server_error', status: 500, layout:'application', content_type: 'text/html'
  end

  def error_403_forbidden(exception=nil)
    logger.debug "# error_403_forbidden"
    if exception
      logger.debug "#{exception.class}:#{exception.message}"
      logger.debug exception.backtrace.first
    end

    @error_title = '403 error'

    render template: 'errors/403_forbidden', status: 403, layout:'application', content_type: 'text/html'
  end

  def error_400_invalied(exception=nil)
    logger.debug "# error_400_invalied"
    if exception
      logger.debug "#{exception.class}:#{exception.message}"
      logger.debug exception.backtrace.first
    end

    @error_title = '400_error'
    @msg = exception.class.to_s == exception.message ? "不正なアクセス" : exception.message

    render template: 'errors/400_invalied', status:400, layout:'application', content_type: 'text/html'
  end

  def access_denied(exception)
    redirect_to root_path, notice: "only admin users role can access the page you've accessed."
  end

  def authenticate_admin_user!
    authenticate_user!

  # current_userはdevise提供のメソッドです。
  # 権限ユーザのroleについては、好きな方法でよいです。（自分の場合、has_roleメソッドで実装）
    unless current_user.has_role 'admin'
      flash[:alert] = "管理者用ページです。権限があるアカウントでログインしてください。"
      redirect_to root_path
    end
  end

  def current_admin_user
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end

  def buddix
    @pre_title = "BuddiXとは"
  end

  def terms_of_service
    @pre_title = "利用規約"
  end

  def privacypolicy
    @pre_title = "プライバシーポリシー"
  end
  
  def corp
    @pre_title = "corp"
  end

  def faq
    @pre_title = "FAQ"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_sign_in!, only: [:destroy]
  before_action :set_user, only: [:create]

  def new
  end

  def create
    if @user.authenticate(session_params[:password])
      sign_in(@user)
      redirect_to root_path
    else
      flash.now[:danger] = t('.flash.invalid_password')
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to login_path
  end

  private
    def set_user
      @user = User.find_by!(mail: session_params[:mail])
    rescue
      flash.now[:danger] = t('.flash.invalid_mail')
      render action: 'new'
    end

    def session_params
      params.require(:session).permit(:mail, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
      @user = User.new
  end

  def create
    if env['omniauth.auth'].present?
      # Facebookログイン
      @user  = User.from_omniauth(env['omniauth.auth'])
      result = @user.save(context: :facebook_login)
      fb = "Facebook"
    else
      # 通常サインアップ
      @user  = User.new(user_params)
      result = @user.save
      fb = ""
    end
    if result
      sign_in @user
      flash[:success] = "#{fb}ログインしました。"
      redirect_to @user
    else
      if fb.present?
        redirect_to auth_failure_path
      else
        render 'new'
      end
    end
  end

  def checkmail
    @mailadress = session[:temp_mail_for_check_mail]
    session[:last_access_path] = session[:last_access_path_tmp]
    session[:last_access_path_tmp] = nil
    flash[:notice] = nil
  end

private
  def user_params
     params.require(:user).permit(:name, :mail, :password, :password_confirmation)
  end

end

app/controllers/users_info_controller.rb
class UsersInfoController < ApplicationController

  def new
    @pre_title = "ギフト申請"
    @users_info = UsersInfo.new
  end

  def create
    users_info = UsersInfo.new(users_info_params)
    if users_info.save
      redirect_to my_page_path, notice: "ユーザ情報登録しました。"
    else
      render users_info_path
    end
  end

  private
    def users_info_params
      params.require(:users_info).permit(:first_name, :last_name, :hundle_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/top.html.erb
<%= react_component('TestBox') %>

app/views/index/buddix.html.slim
h1 BuddiXとは

#hello
  = "{{message}}"
app

app/views/index/corp.html.slim
h1 運営情報

app/views/index/faq.html.slim
h1 FAQ

app/views/index/index.html.slim
.index-bg
  = image_tag('index/index_bg.png')

  .index-logo
    = image_tag('index/index_logo.png')

  p.login-button
   = link_to "ログイン", new_user_session_path, class:'link-button'
  p.signup-button
   = link_to "新規登録", registration_path, class:'link-button'

app/views/index/privacypolicy.html.slim
h1 Privacypolicy

app/views/index/terms_of_service.html.slim
h1 Terms of Service

app/views/layouts/_footer.html.slim
div#footer-menu
  ul
    li = link_to "BuddiXとは", buddix_info_path, class: "footer-menu-column"
    li = link_to "利用規約", terms_of_service_path, class: "footer-menu-column"
    li = link_to "FAQ", faq_path, class: "footer-menu-column"
    li = link_to "運営情報", corp_path, class: "footer-menu-column"

app/views/layouts/_head.html.slim
meta content="text/html"
meta charset="utf-8"
meta http-equiv="Content_Type"
meta name="BuddiX (バディックス )"

= render "layouts/title"
= csrf_meta_tags
/= render "layouts/favicons"
= render "layouts/site_name_json_ld"

= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_pack_tag 'application'

app/views/layouts/_header.html.slim
div#header
  .page_logo
    //=image_tag('header/header.png')

  form action="/" name="search" method="get"
    dl.search
      dt
        input type="text" name="search" placeholder="Search"
        dd
          button
            span

  //- if user_signed_in?
    .log-out
      button = link_to "ログアウト", destroy_user_session_path, style:"text-decoration:none"

app/views/layouts/_site_name_json_ld.html.erb
<script type="application/ld+json">
  { "@context" : "http://schema.org",
    "@type" : "Website",
    "name" : "BuddiX",
    /"url" : = root_url,
    "producer" : {
          "@type" : "Person",
          "familyName" : "Yuki",
          "givenName" : "Shirota",
          "name" : "城田右記",
          "@type" : "Person",
          "familyName" : "Taishi",
          "givenName" : "Murakami",
          "name" : "村上太惟志" ,
          "@type" : "Person",
          "familyName" : "Ibuki",
          "givenName" : "Oshima",
          "name" : "大島一武輝"
        }
    }
</script>

app/views/layouts/_title.html.slim
title
  - if @error_title
    = @error_title + '-' + @root_title
  - elsif @pre_title
    = @pre_title + '-' + @root_title
  - else
    = page_title

app/views/layouts/application.html.slim
doctype html
html
  head
    = render "layouts/head"
  body
    = render "layouts/header" unless (controller_name == "index" && action_name == "index") || (controller_name == "users_info" && action_name == "new")

    = flash[:notice]

    = yield

    =render "layouts/footer" unless controller_name == "users_info" && action_name == "new"

app/views/users/_sign_up.html.slim
.sign-in-up
  .login-box
    h1 ログイン
    - form_for(resource, as: resource_name, url: user_session_path(resource_name), html:{id:"login"}) do |f|
      .field
        = f.label :email
        = f.email_field :email, autocomplete: "email", placeholder:"Email"

      .field
        = f.label :password
        = f.password_field :password, autocomplete: "off"

      .login-checkbox
        = f.check_box :remember_me, {id: "login-checkbox", class:"valign", checked:true}, true, false
        label.valign for="login-checkbox"
          | ログイン情報を保持する
      .login-button
        button type="submit"
          | ログイン
      h2 Facebookアカウントでログインした方
      .facebook-button
        = link_to root_path, class:"facebook-button-link" do
          | Facebookでログイン

  .sign-up-box
  h1 新規登録
  - form_for(resource, as: resource_name, url: registration_path, html:{id:"signup", class:"signup-box-form"}) do |f|
    .field
      = f.label :email
      = f.email_field :email, autofocus: true, autocomplete: "email"

    .field
      = f.label :password
      - if @minimum_password_length
      em #{@minimum_password_length} characters minimum
      br
      = f.password_field :password, autocomplete: "off"

    .field
      = f.label :password_confirmation
      = f.password_field :password_confirmation, autocomplete: "off"

    .signup-button
      button type="submit"
        | 新規登録

    .signup-box-buttons
      .mail-button
        a.mail-button-link
          | メールアドレスで登録
      .facebook-button
        h2 Facebookをお持ちの方
        = link_to root_path, class: "facebook-button-link" do
          | Facebookで登録する
      .warning-notice
        .contract
          | アカウントを作成することにより、
          = link_to "利用規約", terms_of_service_path, target:"_blank"
          | および
          = link_to "プライバシーポリシー", privacypolicy_path, target:"_blank"
          | に同意されたものとさせていただきます

app/views/users/checkmail.html.slim
h2 Please check your email!!

p your adress :　#{@mailadress}

app/views/users/create.html.slim
h1 Users#create
p Find me in app/views/users/create.html.slim